services:
  test:
    build:
      context: .
      dockerfile: Dockerfile
    command: pytest -v --import-mode=importlib
    volumes:
      - .:/app
    environment:
      - POSTGRES_SERVER=db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=cinerental_test
      - TESTING=true
      - PYTHONPATH=/app:/app/backend:/app/tests
    depends_on:
      db:
        condition: service_healthy
    networks:
      - test-network

  db:
    image: postgres:14
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=cinerental_test
    ports:
      - "5432:5432"
    networks:
      - test-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

networks:
  test-network:
    driver: bridge
