name: act-rental-test

services:
  test:
    build:
      context: .
      dockerfile: Dockerfile.test
    volumes:
      - ./backend:/app/backend
      - ./tests:/app/tests
      - ./migrations:/app/migrations
      - ./docker:/app/docker
      - ./media:/app/media
      - ./static:/app/static
      - ./templates:/app/templates
      - ./frontend:/app/frontend
      - ./alembic.ini:/app/alembic.ini
      - ./pyproject.toml:/app/pyproject.toml
      - ./htmlcov:/app/htmlcov
    environment:
      - POSTGRES_SERVER=test-db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=act_rental_test
      - REDIS_HOST=test-redis
      - REDIS_PASSWORD=
      - TESTING=1
      - ENVIRONMENT=testing
      - SECRET_KEY=test-secret-key
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
    depends_on:
      test-db:
        condition: service_healthy
      test-redis:
        condition: service_healthy
    networks:
      - test-network

  test-db:
    image: postgres:15
    tmpfs:
      - /var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - "5433:5432"
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - test-network

  test-redis:
    image: redis:7
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - test-network

networks:
  test-network:
    driver: bridge
