name: act-rental-test

services:
  test:
    build:
      context: .
      target: runtime
      args:
        ENV_TYPE: test
        INSTALL_PLAYWRIGHT_DEPS: true
        INSTALL_PLAYWRIGHT: true
    entrypoint: ./docker/run-tests.sh
    volumes:
      - ./:/app
    environment:
      - POSTGRES_SERVER=test_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=act_rental_test
      - REDIS_HOST=redis
      - REDIS_PASSWORD=
      - TESTING=1
      - SECRET_KEY=test-secret-key
      - ENVIRONMENT=testing
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
    depends_on:
      test_db:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - act-rental_network
    command: >
      bash -c "
        ./docker/wait-for.sh test_db:5432 -t 60 -- echo 'Waiting for PostgreSQL...' &&
        ./docker/wait-for.sh redis:6379 -t 60 -- echo 'Waiting for Redis...' &&
        echo 'Running migrations...' &&
        alembic stamp head &&
        echo 'Running tests...' &&
        pytest ${TEST_PATH:-tests/} -v
      "

  test_db:
    image: postgres:14-alpine
    tmpfs:
      - /var/lib/postgresql/data
    environment:
      - POSTGRES_DB=act_rental_test
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - "5433:5432"
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
    networks:
      - act-rental_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    # Use the same redis image as in the main docker-compose
    # for tests, a simple configuration is sufficient
    image: redis:6-alpine
    command: redis-server --appendonly yes
    networks:
      - act-rental_network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5

networks:
  act-rental_network:
    driver: bridge
