version: '3.8'

services:
  postgres:
    image: postgres:14-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=act-rental
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - act-rental_postgres_data:/var/lib/postgresql/data
      - /tmp/pgdata_extract:/tmp/pgdata_extract
    command: /bin/bash -c "rm -rf /var/lib/postgresql/data/pgdata/* && cp -r /tmp/pgdata_extract/pgdata/* /var/lib/postgresql/data/pgdata/ && chown -R postgres:postgres /var/lib/postgresql/data/pgdata && chmod -R 700 /var/lib/postgresql/data/pgdata && postgres -c 'max_connections=100'"
    user: root

volumes:
  act-rental_postgres_data:
    external: true
