import { Category } from './category';

export enum EquipmentStatus {
  AVAILABLE = 'AVAILABLE',
  RENTED = 'RENTED',
  MAINTENANCE = 'MAINTENANCE',
  BROKEN = 'BROKEN',
  RETIRED = 'RETIRED'
}

export interface Equipment {
  id: number;
  name: string;
  description?: string;
  serial_number?: string;
  barcode: string;
  category_id: number;
  status: EquipmentStatus;
  replacement_cost: number;
  notes?: string;
  created_at?: string;
  updated_at?: string;
  // Relationships
  category?: Category;
  category_name?: string;
}

export interface EquipmentCreate {
  name: string;
  description?: string;
  serial_number?: string;
  // barcode is usually generated by backend, but might be manually entered?
  // Checking backend logic: usually auto-generated if not provided, or strictly auto-generated.
  // We'll leave it optional in create if backend handles it, or required if frontend must supply.
  // Based on model, it's non-nullable.
  category_id: number;
  status?: EquipmentStatus;
  replacement_cost: number;
  notes?: string;
}

export type EquipmentUpdate = Partial<EquipmentCreate> & {
  id: number;
};
