"""Change replacement_cost to Integer

Revision ID: f21be8dd14dc
Revises: 2a58625a591b
Create Date: 2025-04-10 17:57:42.186096+00:00

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'f21be8dd14dc'
down_revision: Union[str, None] = '2a58625a591b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'equipment',
        'replacement_cost',
        existing_type=sa.NUMERIC(precision=10, scale=2),
        type_=sa.Integer(),
        existing_nullable=False,
    )
    op.drop_index('ix_projects_deleted_at', table_name='projects')
    op.create_index(
        op.f('ix_projects_created_at'), 'projects', ['created_at'], unique=False
    )
    op.create_index(
        op.f('ix_projects_updated_at'), 'projects', ['updated_at'], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_projects_updated_at'), table_name='projects')
    op.drop_index(op.f('ix_projects_created_at'), table_name='projects')
    op.create_index('ix_projects_deleted_at', 'projects', ['deleted_at'], unique=False)
    op.alter_column(
        'equipment',
        'replacement_cost',
        existing_type=sa.Integer(),
        type_=sa.NUMERIC(precision=10, scale=2),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
