"""add_timestamp_indexes

Revision ID: df30ee064518
Revises: 3facc5612e70
Create Date: 2025-01-24 21:35:53.840845+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'df30ee064518'
down_revision: Union[str, None] = '3facc5612e70'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('bookings', 'client_id', existing_type=sa.INTEGER(), nullable=False)
    op.alter_column(
        'bookings', 'equipment_id', existing_type=sa.INTEGER(), nullable=False
    )
    op.alter_column(
        'bookings',
        'created_at',
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
        existing_server_default=sa.text('now()'),
    )
    op.alter_column(
        'bookings',
        'updated_at',
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
        existing_server_default=sa.text('now()'),
    )
    op.create_index(
        op.f('ix_bookings_booking_status'), 'bookings', ['booking_status'], unique=False
    )
    op.create_index(
        op.f('ix_bookings_created_at'), 'bookings', ['created_at'], unique=False
    )
    op.create_index(
        op.f('ix_bookings_payment_status'), 'bookings', ['payment_status'], unique=False
    )
    op.create_index(
        op.f('ix_bookings_updated_at'), 'bookings', ['updated_at'], unique=False
    )
    op.alter_column(
        'categories',
        'created_at',
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
        existing_server_default=sa.text('now()'),
    )
    op.alter_column(
        'categories',
        'updated_at',
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
        existing_server_default=sa.text('now()'),
    )
    op.create_index(
        op.f('ix_categories_created_at'), 'categories', ['created_at'], unique=False
    )
    op.create_index(
        op.f('ix_categories_updated_at'), 'categories', ['updated_at'], unique=False
    )
    op.alter_column(
        'clients', 'email', existing_type=sa.VARCHAR(length=255), nullable=False
    )
    op.alter_column(
        'clients',
        'created_at',
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
        existing_server_default=sa.text('now()'),
    )
    op.alter_column(
        'clients',
        'updated_at',
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
        existing_server_default=sa.text('now()'),
    )
    op.create_index(
        op.f('ix_clients_created_at'), 'clients', ['created_at'], unique=False
    )
    op.create_index(
        op.f('ix_clients_deleted_at'), 'clients', ['deleted_at'], unique=False
    )
    op.create_index(op.f('ix_clients_status'), 'clients', ['status'], unique=False)
    op.create_index(
        op.f('ix_clients_updated_at'), 'clients', ['updated_at'], unique=False
    )
    op.alter_column(
        'documents', 'client_id', existing_type=sa.INTEGER(), nullable=False
    )
    op.alter_column(
        'documents',
        'created_at',
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
        existing_server_default=sa.text('now()'),
    )
    op.alter_column(
        'documents',
        'updated_at',
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
        existing_server_default=sa.text('now()'),
    )
    op.create_index(
        op.f('ix_documents_created_at'), 'documents', ['created_at'], unique=False
    )
    op.create_index(op.f('ix_documents_type'), 'documents', ['type'], unique=False)
    op.create_index(
        op.f('ix_documents_updated_at'), 'documents', ['updated_at'], unique=False
    )
    op.alter_column(
        'equipment',
        'serial_number',
        existing_type=sa.VARCHAR(length=100),
        nullable=False,
    )
    op.alter_column(
        'equipment', 'barcode', existing_type=sa.VARCHAR(length=100), nullable=False
    )
    op.alter_column(
        'equipment', 'category_id', existing_type=sa.INTEGER(), nullable=False
    )
    op.alter_column(
        'equipment',
        'created_at',
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
        existing_server_default=sa.text('now()'),
    )
    op.alter_column(
        'equipment',
        'updated_at',
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
        existing_server_default=sa.text('now()'),
    )
    op.create_index(
        op.f('ix_equipment_created_at'), 'equipment', ['created_at'], unique=False
    )
    op.create_index(
        op.f('ix_equipment_deleted_at'), 'equipment', ['deleted_at'], unique=False
    )
    op.create_index(op.f('ix_equipment_status'), 'equipment', ['status'], unique=False)
    op.create_index(
        op.f('ix_equipment_updated_at'), 'equipment', ['updated_at'], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_equipment_updated_at'), table_name='equipment')
    op.drop_index(op.f('ix_equipment_status'), table_name='equipment')
    op.drop_index(op.f('ix_equipment_deleted_at'), table_name='equipment')
    op.drop_index(op.f('ix_equipment_created_at'), table_name='equipment')
    op.alter_column(
        'equipment',
        'updated_at',
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
        existing_server_default=sa.text('now()'),
    )
    op.alter_column(
        'equipment',
        'created_at',
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
        existing_server_default=sa.text('now()'),
    )
    op.alter_column(
        'equipment', 'category_id', existing_type=sa.INTEGER(), nullable=True
    )
    op.alter_column(
        'equipment', 'barcode', existing_type=sa.VARCHAR(length=100), nullable=True
    )
    op.alter_column(
        'equipment',
        'serial_number',
        existing_type=sa.VARCHAR(length=100),
        nullable=True,
    )
    op.drop_index(op.f('ix_documents_updated_at'), table_name='documents')
    op.drop_index(op.f('ix_documents_type'), table_name='documents')
    op.drop_index(op.f('ix_documents_created_at'), table_name='documents')
    op.alter_column(
        'documents',
        'updated_at',
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
        existing_server_default=sa.text('now()'),
    )
    op.alter_column(
        'documents',
        'created_at',
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
        existing_server_default=sa.text('now()'),
    )
    op.alter_column('documents', 'client_id', existing_type=sa.INTEGER(), nullable=True)
    op.drop_index(op.f('ix_clients_updated_at'), table_name='clients')
    op.drop_index(op.f('ix_clients_status'), table_name='clients')
    op.drop_index(op.f('ix_clients_deleted_at'), table_name='clients')
    op.drop_index(op.f('ix_clients_created_at'), table_name='clients')
    op.alter_column(
        'clients',
        'updated_at',
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
        existing_server_default=sa.text('now()'),
    )
    op.alter_column(
        'clients',
        'created_at',
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
        existing_server_default=sa.text('now()'),
    )
    op.alter_column(
        'clients', 'email', existing_type=sa.VARCHAR(length=255), nullable=True
    )
    op.drop_index(op.f('ix_categories_updated_at'), table_name='categories')
    op.drop_index(op.f('ix_categories_created_at'), table_name='categories')
    op.alter_column(
        'categories',
        'updated_at',
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
        existing_server_default=sa.text('now()'),
    )
    op.alter_column(
        'categories',
        'created_at',
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
        existing_server_default=sa.text('now()'),
    )
    op.drop_index(op.f('ix_bookings_updated_at'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_payment_status'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_created_at'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_booking_status'), table_name='bookings')
    op.alter_column(
        'bookings',
        'updated_at',
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
        existing_server_default=sa.text('now()'),
    )
    op.alter_column(
        'bookings',
        'created_at',
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
        existing_server_default=sa.text('now()'),
    )
    op.alter_column(
        'bookings', 'equipment_id', existing_type=sa.INTEGER(), nullable=True
    )
    op.alter_column('bookings', 'client_id', existing_type=sa.INTEGER(), nullable=True)
    # ### end Alembic commands ###
