"""add_quantity_to_bookings

Revision ID: 43401ae3c3c4
Revises: f21be8dd14dc
Create Date: 2025-04-15 13:51:00.082287+00:00

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '43401ae3c3c4'
down_revision: Union[str, None] = 'f21be8dd14dc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Add quantity column as nullable first
    op.add_column(
        'bookings',
        sa.Column(
            'quantity',
            sa.Integer(),
            nullable=True,
            comment='Quantity of equipment items in this booking',
        ),
    )

    # Update existing records to have quantity = 1
    bookings = sa.table('bookings', sa.Column('quantity', sa.Integer()))
    op.execute(
        bookings.update().where(bookings.c.quantity.is_(None)).values(quantity=1)
    )

    # Now make it not nullable
    op.alter_column('bookings', 'quantity', existing_type=sa.Integer(), nullable=False)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bookings', 'quantity')
    # ### end Alembic commands ###
