"""Add show_in_print_overview column to categories table

Revision ID: ca195814c916
Revises: 43401ae3c3c4
Create Date: 2025-05-13 15:16:16.343862+00:00

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'ca195814c916'
down_revision: Union[str, None] = '43401ae3c3c4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'categories',
        sa.Column(
            'show_in_print_overview',
            sa.Boolean(),
            server_default=sa.text('true'),
            nullable=False,
            comment='Whether to show this category as a header in print forms',
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('categories', 'show_in_print_overview')
    # ### end Alembic commands ###
