"""merge_first_and_last_name

Revision ID: 2dadcbaa2fea
Revises: ce486ea5be90
Create Date: 2025-03-17 21:25:36.935150+00:00

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2dadcbaa2fea'
down_revision: Union[str, None] = 'ce486ea5be90'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_barcode_sequences_category_id', table_name='barcode_sequences')
    op.drop_index('ix_barcode_sequences_created_at', table_name='barcode_sequences')
    op.drop_index('ix_barcode_sequences_deleted_at', table_name='barcode_sequences')
    op.drop_index('ix_barcode_sequences_updated_at', table_name='barcode_sequences')
    op.drop_table('barcode_sequences')
    op.drop_index('ix_bookings_end_date', table_name='bookings')
    op.drop_index('ix_bookings_start_date', table_name='bookings')
    op.drop_column('bookings', 'actual_return_date')
    op.drop_index('ix_categories_deleted_at', table_name='categories')
    op.drop_index('ix_categories_name', table_name='categories')
    op.create_unique_constraint(None, 'categories', ['name'])
    op.drop_constraint('categories_parent_id_fkey', 'categories', type_='foreignkey')
    op.create_foreign_key(
        None, 'categories', 'categories', ['parent_id'], ['id'], ondelete='RESTRICT'
    )

    # Add name column as nullable first
    op.add_column('clients', sa.Column('name', sa.String(length=200), nullable=True))

    # Populate name column with concatenated first_name and last_name
    op.execute("UPDATE clients SET name = first_name || ' ' || last_name")

    # Make name column not nullable after data migration
    op.alter_column('clients', 'name', nullable=False)

    op.alter_column(
        'clients',
        'passport_number',
        existing_type=sa.VARCHAR(length=50),
        type_=sa.String(length=20),
        existing_nullable=False,
    )
    op.drop_index('ix_clients_email', table_name='clients')
    op.create_unique_constraint(None, 'clients', ['passport_number'])
    op.create_unique_constraint(None, 'clients', ['email'])
    op.create_unique_constraint(None, 'clients', ['phone'])

    # Now drop the old columns
    op.drop_column('clients', 'last_name')
    op.drop_column('clients', 'first_name')

    op.add_column(
        'documents', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True)
    )
    op.create_index(
        op.f('ix_documents_booking_id'), 'documents', ['booking_id'], unique=False
    )
    op.create_index(
        op.f('ix_documents_client_id'), 'documents', ['client_id'], unique=False
    )
    op.alter_column(
        'equipment',
        'notes',
        existing_type=sa.VARCHAR(length=1000),
        type_=sa.String(length=5000),
        existing_nullable=True,
    )
    op.drop_index(
        'idx_equipment_barcode_search', table_name='equipment', postgresql_using='gin'
    )
    op.drop_index(
        'idx_equipment_description_search',
        table_name='equipment',
        postgresql_using='gin',
    )
    op.drop_index(
        'idx_equipment_name_search', table_name='equipment', postgresql_using='gin'
    )
    op.drop_index(
        'idx_equipment_serial_number_search',
        table_name='equipment',
        postgresql_using='gin',
    )
    op.drop_index(
        'ix_global_barcode_sequence_created_at', table_name='global_barcode_sequence'
    )
    op.drop_index(
        'ix_global_barcode_sequence_deleted_at', table_name='global_barcode_sequence'
    )
    op.drop_index(
        'ix_global_barcode_sequence_updated_at', table_name='global_barcode_sequence'
    )
    op.drop_index('ix_users_deleted_at', table_name='users')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_users_deleted_at', 'users', ['deleted_at'], unique=False)
    op.create_index(
        'ix_global_barcode_sequence_updated_at',
        'global_barcode_sequence',
        ['updated_at'],
        unique=False,
    )
    op.create_index(
        'ix_global_barcode_sequence_deleted_at',
        'global_barcode_sequence',
        ['deleted_at'],
        unique=False,
    )
    op.create_index(
        'ix_global_barcode_sequence_created_at',
        'global_barcode_sequence',
        ['created_at'],
        unique=False,
    )
    op.create_index(
        'idx_equipment_serial_number_search',
        'equipment',
        ['serial_number'],
        unique=False,
        postgresql_using='gin',
    )
    op.create_index(
        'idx_equipment_name_search',
        'equipment',
        ['name'],
        unique=False,
        postgresql_using='gin',
    )
    op.create_index(
        'idx_equipment_description_search',
        'equipment',
        ['description'],
        unique=False,
        postgresql_using='gin',
    )
    op.create_index(
        'idx_equipment_barcode_search',
        'equipment',
        ['barcode'],
        unique=False,
        postgresql_using='gin',
    )
    op.drop_index(op.f('ix_documents_client_id'), table_name='documents')
    op.drop_index(op.f('ix_documents_booking_id'), table_name='documents')
    op.drop_column('documents', 'deleted_at')

    # Add back first_name and last_name columns as nullable first
    op.add_column(
        'clients',
        sa.Column(
            'first_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True
        ),
    )
    op.add_column(
        'clients',
        sa.Column(
            'last_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True
        ),
    )

    # Split name into first_name and last_name
    # This is a simplified approach - assumes first word is first_name
    # and rest is last_name
    op.execute(
        """
    UPDATE clients
    SET
        first_name = SUBSTRING(name FROM 1 FOR POSITION(' ' IN name) - 1),
        last_name = SUBSTRING(name FROM POSITION(' ' IN name) + 1)
    """
    )

    # Make first_name and last_name not nullable
    op.alter_column('clients', 'first_name', nullable=False)
    op.alter_column('clients', 'last_name', nullable=False)

    # Now drop name column
    op.drop_constraint('clients_email_key', 'clients', type_='unique')
    op.drop_constraint('clients_phone_key', 'clients', type_='unique')
    op.drop_constraint('clients_passport_number_key', 'clients', type_='unique')
    op.create_index('ix_clients_email', 'clients', ['email'], unique=True)
    op.alter_column(
        'clients',
        'passport_number',
        existing_type=sa.String(length=20),
        type_=sa.VARCHAR(length=50),
        existing_nullable=False,
    )
    op.drop_column('clients', 'name')
    op.drop_constraint('categories_parent_id_fkey', 'categories', type_='foreignkey')
    op.create_foreign_key(
        'categories_parent_id_fkey',
        'categories',
        'categories',
        ['parent_id'],
        ['id'],
        ondelete='SET NULL',
    )
    op.drop_constraint('categories_name_key', 'categories', type_='unique')
    op.create_index('ix_categories_name', 'categories', ['name'], unique=False)
    op.create_index(
        'ix_categories_deleted_at', 'categories', ['deleted_at'], unique=False
    )
    op.add_column(
        'bookings',
        sa.Column(
            'actual_return_date',
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.create_index('ix_bookings_start_date', 'bookings', ['start_date'], unique=False)
    op.create_index('ix_bookings_end_date', 'bookings', ['end_date'], unique=False)
    op.create_table(
        'barcode_sequences',
        sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column('category_id', sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column(
            'last_number',
            sa.INTEGER(),
            server_default=sa.text('0'),
            autoincrement=False,
            nullable=False,
            comment='Last used sequence number',
        ),
        sa.Column(
            'created_at',
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text('now()'),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            'updated_at',
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text('now()'),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            'deleted_at',
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ['category_id'],
            ['categories.id'],
            name='barcode_sequences_category_id_fkey',
            ondelete='CASCADE',
        ),
        sa.PrimaryKeyConstraint('id', name='barcode_sequences_pkey'),
        sa.UniqueConstraint('category_id', name='uq_category'),
    )
    op.create_index(
        'ix_barcode_sequences_updated_at',
        'barcode_sequences',
        ['updated_at'],
        unique=False,
    )
    op.create_index(
        'ix_barcode_sequences_deleted_at',
        'barcode_sequences',
        ['deleted_at'],
        unique=False,
    )
    op.create_index(
        'ix_barcode_sequences_created_at',
        'barcode_sequences',
        ['created_at'],
        unique=False,
    )
    op.create_index(
        'ix_barcode_sequences_category_id',
        'barcode_sequences',
        ['category_id'],
        unique=False,
    )
    # ### end Alembic commands ###
