"""remove_unique_constraints_on_client_email_phone

Revision ID: 0d544e3b71ec
Revises: dc9988c1f5cb
Create Date: 2025-03-18 15:03:35.461322+00:00

"""

from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '0d544e3b71ec'
down_revision: Union[str, None] = 'dc9988c1f5cb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('clients_email_key', 'clients', type_='unique')
    op.drop_constraint('clients_phone_key', 'clients', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('clients_phone_key', 'clients', ['phone'])
    op.create_unique_constraint('clients_email_key', 'clients', ['email'])
    # ### end Alembic commands ###
