"""change_booking_default_status_to_active

Revision ID: 1776b619f139
Revises: 0d544e3b71ec
Create Date: 2025-03-18 15:49:31.568592+00:00

"""

from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '1776b619f139'
down_revision: Union[str, None] = '0d544e3b71ec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        "ALTER TABLE bookings ALTER COLUMN booking_status "
        "SET DEFAULT 'ACTIVE'::bookingstatus"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        "ALTER TABLE bookings ALTER COLUMN booking_status "
        "SET DEFAULT 'PENDING'::bookingstatus"
    )
    # ### end Alembic commands ###
