name: Auto Close Issues on Develop

on:
  push:
    branches: [ develop ]

jobs:
  auto-close-issues:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Auto close issues
        uses: actions/github-script@v7
        with:
          script: |
            const { context } = require('@actions/github');

            // Get commit messages from the push
            const commits = context.payload.commits || [];

            for (const commit of commits) {
              const message = commit.message;
              console.log(`Checking commit: ${message}`);

              // Look for issue closing keywords
              const closeKeywords = /(?:close[sd]?|fix(?:e[sd])?|resolve[sd]?)\s+#(\d+)/gi;
              let match;

              while ((match = closeKeywords.exec(message)) !== null) {
                const issueNumber = parseInt(match[1]);
                console.log(`Found issue reference: #${issueNumber}`);

                try {
                  // Close the issue
                  await github.rest.issues.update({
                    owner: context.repo.owner,
                    repo: context.repo.repo,
                    issue_number: issueNumber,
                    state: 'closed'
                  });

                  // Add a comment explaining the closure
                  await github.rest.issues.createComment({
                    owner: context.repo.owner,
                    repo: context.repo.repo,
                    issue_number: issueNumber,
                    body: `Automatically closed by commit ${commit.id} in develop branch.`
                  });

                  console.log(`Successfully closed issue #${issueNumber}`);
                } catch (error) {
                  console.error(`Failed to close issue #${issueNumber}:`, error);
                }
              }
            }
