name: Deploy Frontends

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Backend + MVP Frontend
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/cinerental-backend:latest

      - name: Build and push Vue3 Frontend
        uses: docker/build-push-action@v5
        with:
          context: ./frontend-vue3
          file: ./frontend-vue3/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/cinerental-vue3:latest

      - name: Deploy to server
        run: |
          echo "Dual frontend deployment:"
          echo "- MVP Frontend: Integrated with FastAPI backend"
          echo "- Vue3 Frontend: Available at /v3 route via Nginx proxy"
          echo "- Soft migration: Users can access both frontends during transition"
