name: Run Tests

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  test:
    name: Run Tests in Docker
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Cache Docker layers
        uses: actions/cache@v4
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Create .env file
        run: |
          echo "ENVIRONMENT=testing" > .env
          echo "POSTGRES_USER=postgres" >> .env
          echo "POSTGRES_PASSWORD=postgres" >> .env
          echo "POSTGRES_DB=cinerental_test" >> .env
          echo "POSTGRES_HOST_AUTH_METHOD=trust" >> .env
          echo "SECRET_KEY=test-secret-key" >> .env
          echo "DEBUG=false" >> .env
          echo "TESTING=1" >> .env

      - name: Build and start containers
        run: |
          docker compose build test test_db redis
          docker compose up -d test_db redis

      - name: Wait for services to be ready
        run: |
          # Ensure wait-for.sh is executable
          chmod +x docker/wait-for.sh

          # Wait for PostgreSQL using wait-for.sh
          docker compose run --rm --no-deps --entrypoint "./docker/wait-for.sh" test postgres test_db 5432

          # Wait for Redis using wait-for.sh
          docker compose run --rm --no-deps --entrypoint "./docker/wait-for.sh" test redis redis 6379

      - name: Run migrations
        run: |
          docker compose run --rm --no-deps --entrypoint "alembic" test upgrade head

      - name: Run tests
        run: |
          # Создаем временный скрипт для запуска тестов внутри контейнера
          echo "=== Создание временного скрипта для запуска тестов ==="
          cat > run_tests_ci.sh << 'EOF'
          #!/bin/bash
          set -e

          echo "=== Информация о среде ==="
          echo "Python version: $(python --version)"
          echo "Pytest version: $(python -m pytest --version)"
          echo "Working directory: $(pwd)"

          echo "=== Структура директории /app ==="
          ls -la /app

          echo "=== Проверка наличия директории tests ==="
          if [ -d "/app/tests" ]; then
            ls -la /app/tests
          else
            echo "Директория tests не найдена"
            exit 1
          fi

          echo "=== Поиск тестовых файлов ==="
          TEST_FILES=$(find /app -type f -name "test_*.py" | sort)
          echo "$TEST_FILES"

          if [ -z "$TEST_FILES" ]; then
            echo "Тестовые файлы не найдены!"
            exit 1
          fi

          echo "=== Проверка прав доступа ==="
          ls -la /app/tests/unit/
          ls -la /app/tests/integration/
          ls -la /app/tests/e2e/

          echo "=== Проверка конфигурации pytest ==="
          cat /app/pytest.ini

          echo "=== Запуск тестов ==="
          cd /app

          # Запускаем тесты по одному для отладки
          echo "=== Запуск unit тестов ==="
          python -m pytest tests/unit/ -v --no-header -p no:cacheprovider || echo "Unit тесты завершились с ошибкой"

          echo "=== Запуск integration тестов ==="
          python -m pytest tests/integration/ -v --no-header -p no:cacheprovider || echo "Integration тесты завершились с ошибкой"

          echo "=== Запуск e2e тестов ==="
          python -m pytest tests/e2e/ -v --no-header -p no:cacheprovider || echo "E2E тесты завершились с ошибкой"

          echo "=== Запуск всех тестов с покрытием ==="
          python -m pytest tests/ -v --no-header -p no:cacheprovider --cov=backend --cov-report=html --cov-report=term || echo "Тесты с покрытием завершились с ошибкой"
          EOF

          chmod +x run_tests_ci.sh

          # Запускаем контейнер с тестами и выполняем скрипт
          docker compose run --rm --no-deps -v $(pwd)/run_tests_ci.sh:/tmp/run_tests_ci.sh --entrypoint "bash" test /tmp/run_tests_ci.sh

      - name: Copy coverage report from container
        if: success()
        run: |
          # Create directory for coverage reports
          mkdir -p coverage

          # Copy HTML coverage report from container to host
          docker compose run --rm --no-deps --entrypoint "sh" test -c "cp -r htmlcov /app/coverage/ 2>/dev/null || echo 'No htmlcov directory found'"

      - name: Upload coverage report as artifact
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: coverage/htmlcov
          retention-days: 7

      - name: Stop containers
        if: always()
        run: docker compose down
