name: Run Tests

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  test:
    name: Run Tests in Docker
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Cache Docker layers
        uses: actions/cache@v4
        with:
          path: ~/.docker
          key: ${{ runner.os }}-docker-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-docker-

      - name: Build and start containers
        run: |
          docker compose -f docker-compose.test.yml build
          docker compose -f docker-compose.test.yml up -d test-db test-redis

      - name: Run tests
        run: |
          # Create directory for coverage reports
          mkdir -p $(pwd)/coverage/htmlcov
          chmod -R 777 $(pwd)/coverage

          # Run all tests with coverage
          docker compose -f docker-compose.test.yml run --rm \
            -v $(pwd)/coverage:/app/coverage \
            test bash -c "
              echo 'Running unit tests...' && \
              pytest tests/unit/ -v --cov=backend --cov-report=html:/app/coverage/htmlcov/unit || exit 1 && \
              echo 'Running integration tests...' && \
              pytest tests/integration/ -v --cov=backend --cov-report=html:/app/coverage/htmlcov/integration || exit 1 && \
              echo 'Running e2e tests...' && \
              pytest tests/e2e/ -v --cov=backend --cov-report=html:/app/coverage/htmlcov/e2e || exit 1
            "

      - name: Upload coverage report as artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: coverage/htmlcov
          retention-days: 7
          if-no-files-found: warn

      - name: Stop containers
        if: always()
        run: |
          echo "Stopping all containers..."
          docker compose -f docker-compose.test.yml down -v
